spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: ${PROFILE}
  application:
    name: parse-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: ${RABBITMQ_PORT}
    template:
      default-receive-queue: ${TEMP_DEFAULT_QUEUE}
      exchange: ${TEMP_EXCHANGE}
      routing-key: ${TEMP_ROUTING_KEY}
      vhost: ${VHOST}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    database: ${JPA_DB}
    database-platform: ${DIALECT}
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ${UNSPECIFIED}

server:
  port: ${PARSE_SERVICE_DEV_PORT}