version: '3.3'
services:
  web-provider:
    container_name: web-provider
    image: 'rstq1337/web-provider:v4'
    depends_on:
      - rabbitmq
      - postgres
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      TEMP_DEFAULT_QUEUE: ${TEMP_DEFAULT_QUEUE}
      TEMP_EXCHANGE: ${TEMP_EXCHANGE}
      TEMP_ROUTING_KEY: ${TEMP_ROUTING_KEY}
  parse-service:
    container_name: parse-service
    image: 'rstq1337/parse-service:v3'
    depends_on:
      - rabbitmq
      - postgres
    ports:
        - "8086:8081"
    environment:
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_USER: ${RABBITMQ_USERNAME}
        RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        TEMP_DEFAULT_QUEUE: ${TEMP_DEFAULT_QUEUE}
        SPRING_DATASOURCE_URL: ${DB_URL}
        SPRING_DATASOURCE_USERNAME: ${DB_USER}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
  rabbitmq:
    container_name: rabbitmq
    image: 'rstq1337/rabbitmq:v1'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: always
  postgres:
    image: 'postgres:14.5-bullseye'
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
volumes:
    postgres:
      driver: local